<?php
global $contextFile, $shaclDir, $generatedDir;
$generatedDir="generated";
$contextFile="generated/context.json";
$shaclDir="generated/shacl";

//global $markDownFile="group.md";


function autonote(){echo "autogenerated...";}
function init () {echo "**autogenerated from model.php, do not edit directly, edit modelphp instead**
";
}



function headerFooter($contextFile, $shaclDir){
    //context.json
    $contextStr = file_get_contents($contextFile);

    // removes last comma
    $contextStr = substr_replace(trim($contextStr) ,"",-1);

    $contextPrefix ='{
	"dataid": "http://dataid.dbpedia.org/ns/core#",
  "dcv": "http://dataid.dbpedia.org/ns/cv#",
	"rdfs": "http://www.w3.org/2000/01/rdf-schema#",
	"dct": "http://purl.org/dc/terms/",
	"dcat": "http://www.w3.org/ns/dcat#",
	"xsd": "http://www.w3.org/2001/XMLSchema#",
	"cert": "http://www.w3.org/ns/auth/cert#",
	"dbo": "http://dbpedia.org/ontology/",
	"foaf": "http://xmlns.com/foaf/0.1/",
	"sec": "https://w3id.org/security#",

';

    $contextStr = $contextPrefix .PHP_EOL .$contextStr .PHP_EOL ."}";

    
    file_put_contents($contextFile, $contextStr);



    //prepare shacl files
    $shaclFiles = array_diff(scandir($shaclDir), array('.', '..'));
    foreach($shaclFiles as $shaclFile){

        $shaclStr = file_get_contents("$shaclDir/$shaclFile");

        $prefixes = "@prefix dash: <http://datashapes.org/dash#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix dataid: <http://dataid.dbpedia.org/ns/core#> .
@prefix dct:   <http://purl.org/dc/terms/> .
@prefix dcat:  <http://www.w3.org/ns/dcat#> .
@prefix dcv: <http://dataid.dbpedia.org/ns/cv#> .
@prefix db: <https://databus.dbpedia.org/sys/ont/> .

";

        file_put_contents("$shaclDir/$shaclFile", $prefixes .$shaclStr);
    }

}

function table ($section, $sectionExampleURI, $owl, $shacl, $example, $context){
    global $contextFile, $shaclDir;

    //merge dataid with distribution
	if($section=="distribution"){
		$section="dataid";
		}

    if ($shacl != "missing") {
		file_put_contents("$shaclDir/$section.shacl",$shacl .PHP_EOL .PHP_EOL,FILE_APPEND);
    }

    if ($context !== "missing" && $context !== "duplicate" ){
	    file_put_contents($contextFile,$context.",".PHP_EOL.PHP_EOL,FILE_APPEND);
    }


	//file_put_contents("$examplesDir/$section.example.jsonld",$example .PHP_EOL,FILE_APPEND);

	$mdString = render($owl,$shacl,$example,$context,$section,$sectionExampleURI);

	echo $mdString;

}

function render($owl,$shacl,$example,$context,$section,$sectionExampleURI){
	// prepare context string
	$cstring="";
	if(trim($context)!="duplicate"){
		$cstring = "```json
$context
```
";}
	//prepare example string 
	//TODO change URI
    $exstring= "\"@id\": \"$sectionExampleURI\",
	$example";


	return "
Example (JSON-LD):
```json
{	
$exstring
}
```
Spec (OWL, SHACL, JSON-LD Context)
```turtle
$owl
```
```turtle
$shacl
```
".$cstring."
```";
}
?>
