<?php
global $contextFile, $shaclDir, $generatedDir;
$generatedDir="generated";
$contextFile="generated/context.json";
$shaclDir="generated/shacl";

function autonote(){echo "autogenerated...";}
function init () {echo "**auto-generated from model/*.php via pre-commit hook. Edit in PHP in git and enable hook with `cd .git/hooks && ln -s ../../.githooks/pre-commit pre-commit`**
";
}

function table ($section, $sectionExampleURI, $owl, $shacl, $example, $context){
    global $contextFile, $shaclDir;

    //merge dataid with distribution
	if($section=="distribution"){
		$section="dataid";
		}

    if ($shacl != "missing") {
		file_put_contents("$shaclDir/$section.shacl",$shacl .PHP_EOL .PHP_EOL,FILE_APPEND);
    }

    if ($context !== "missing" && $context !== "duplicate" ){
	    file_put_contents($contextFile,$context.",".PHP_EOL.PHP_EOL,FILE_APPEND);
    }


	//file_put_contents("$examplesDir/$section.example.jsonld",$example .PHP_EOL,FILE_APPEND);

	$mdString = render($owl,$shacl,$example,$context,$section,$sectionExampleURI);

	echo $mdString;

}

function render($owl,$shacl,$example,$context,$section,$sectionExampleURI){
	// prepare context string
	$cstring="";
	if(trim($context)!="duplicate"){
		$cstring = "```javascript
$context
```
";}
	//prepare example string 
	//TODO change URI
    $exstring= "	\"@id\": \"$sectionExampleURI\",
	$example";


	return "
Example (JSON-LD):
```javascript
{	
$exstring
}
```
Spec (OWL, SHACL, JSON-LD Context)
```turtle
$owl
```
```turtle
$shacl
```
".$cstring."";
}
?>
