version: "3.8"  # Updated version for Swarm compatibility
services:
  ${CLIENT_ID}_server:
    image: "databus-rc12"
    environment:
      DATABUS_RESOURCE_BASE_URL: ${DATABUS_RESOURCE_BASE_URL}
      DATABUS_DATABASE_URL: "http://databus_gstore:8080"
      LOOKUP_BASE_URL: "http://lookup:8082"
      DATABUS_OIDC_ISSUER_BASE_URL: ${DATABUS_OIDC_ISSUER_BASE_URL}
      DATABUS_NAME: ${DATABUS_NAME}
      DATABUS_ORG_ICON: ${DATABUS_ORG_ICON}
      DATABUS_BANNER_COLOR: ${DATABUS_BANNER_COLOR}
      DATABUS_OIDC_CLIENT_ID: ${DATABUS_OIDC_CLIENT_ID}
      DATABUS_OIDC_SECRET: ${DATABUS_OIDC_SECRET}
      DATABUS_PRIVATE_MODE: ${DATABUS_PRIVATE_MODE}
      DATABUS_PROXY_SERVER_ENABLE: ${DATABUS_PROXY_SERVER_ENABLE}
      DATABUS_PROXY_SERVER_USE_ACME: ${DATABUS_PROXY_SERVER_USE_ACME}
      DATABUS_PROXY_SERVER_OWN_CERT: ${DATABUS_PROXY_SERVER_OWN_CERT}
      DATABUS_PROXY_SERVER_OWN_CERT_KEY: ${DATABUS_PROXY_SERVER_OWN_CERT_KEY}
      DATABUS_PROXY_SERVER_HOSTNAME: ${DATABUS_PROXY_SERVER_HOSTNAME}
    volumes:
      - ./data/${CLIENT_ID}/dav/:/databus/server/dav/
      - ./data/${CLIENT_ID}/sqlite/:/databus/server/sqlite
      - ./data/${CLIENT_ID}/keypair/:/databus/server/keypair
      - ./data/${CLIENT_ID}/tls/:/tls:ro
      - ./data/${CLIENT_ID}/tls/caddy:/root/.local/share/caddy/
    networks:
      - ${CLIENT_ID}_network
  databus_gstore:
    image: "docker.io/dbpedia/gstore"
    environment:
      STORAGE_USER: ${VIRTUOSO_USER}
      STORAGE_PASS: ${VIRTUOSO_PASSWORD}
      STORAGE_SPARQL_ENDPOINT_URI: http://databus_virtuoso:8890/sparql
    volumes:
      - ./data/${CLIENT_ID}/gstore/repo:/gstore/git
      - ./data/${CLIENT_ID}/gstore/logs:/gstore/logs
    networks:
      - ${CLIENT_ID}_network
  databus_virtuoso:
    image: "docker.io/openlink/virtuoso-opensource-7"
    environment:
      DBA_PASSWORD: ${VIRTUOSO_PASSWORD}
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: ${DATABUS_RESOURCE_BASE_URL}
    ports:
      - "127.0.0.1:${CLIENT_ID}_3003:8890"
    volumes:
      - ./data/${CLIENT_ID}/virtuoso:/database
    entrypoint: /bin/bash -c "
        echo 'grant SPARQL_LOAD_SERVICE_DATA to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SPONGE to \"SPARQL\";' >> /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SELECT_FED to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        /virtuoso-entrypoint.sh
      ""
    networks:
      - ${CLIENT_ID}_network
  databus_lookup:
    image: lookup:dev
    volumes:
      - ./data/index/:/index
      - ../search/servlet-config.yml:/resources/config.yml
    networks:
      - ${CLIENT_ID}_network
networks:
  ${CLIENT_ID}_network:
    driver: overlay