version: "1.0"
indexPath: ./index
cacheSize: 1000000
cleanIndex: true
indexMode: INDEX_SPARQL
sparqlEndpoint: http://localhost:3002/sparql
commitInterval: 1000
indexFields:
  - fieldName: label
    resourceName: resource
    query: >
      SELECT DISTINCT ?resource ?label WHERE {
        {
          GRAPH ?g1 {
            ?resource a <https://dataid.dbpedia.org/databus#Collection> .
          }
          GRAPH ?g2 {
            ?resource <http://purl.org/dc/terms/title> ?label.
          }
        }
        %VALUES%
      }
  - fieldName: label
    resourceName: resource
    query: >
      SELECT DISTINCT ?resource ?label WHERE {
        {
          GRAPH ?g1 {
            ?resource a <https://dataid.dbpedia.org/databus#Group>.
          }
          GRAPH ?g2 {
            ?resource <http://purl.org/dc/terms/title> ?label.
          }
        }
        %VALUES%
      }
  - fieldName: abstract
    resourceName: resource
    query: >
      SELECT DISTINCT ?resource ?abstract WHERE {
        {
          GRAPH ?g1 {
            ?resource a <https://dataid.dbpedia.org/databus#Group>.
          }
          GRAPH ?g2 {
            ?resource <http://purl.org/dc/terms/abstract> ?abstract.
          }
        }
        %VALUES%
      }
  - fieldName: abstract
    resourceName: resource
    query: >
      SELECT DISTINCT ?resource ?abstract WHERE {
        {
          GRAPH ?g1 {
            ?resource a <https://dataid.dbpedia.org/databus#Artifact>.
          }
          GRAPH ?g2 {
            ?resource <http://purl.org/dc/terms/abstract> ?abstract.
          }
        }
        %VALUES%
      }
  - fieldName: label
    resourceName: resource
    query: >
      SELECT DISTINCT ?resource ?label WHERE {
        {
          GRAPH ?g1 {
            ?resource a <https://dataid.dbpedia.org/databus#Artifact>.
          }
          GRAPH ?g2 {
            ?resource <http://purl.org/dc/terms/title> ?label.
          }
        }
        %VALUES%
      }
  - fieldName: label
    resourceName: resource
    query: >
      SELECT DISTINCT ?resource ?label WHERE {
        {
          GRAPH ?g1 {
            ?resource a <https://dataid.dbpedia.org/databus#Version>.
          }
          GRAPH ?g2 {
            ?resource <http://purl.org/dc/terms/title> ?label.
          }
        }
        %VALUES%
      }
  - fieldName: abstract
    resourceName: resource
    query: >
      SELECT DISTINCT ?resource ?abstract WHERE {
        {
          GRAPH ?g1 {
            ?resource a <https://dataid.dbpedia.org/databus#Version>.
          }
          GRAPH ?g2 {
            ?resource <http://purl.org/dc/terms/abstract> ?abstract.
          }
        }
        %VALUES%
      }
  - fieldName: label
    resourceName: artifact
    query: >
      SELECT DISTINCT ?artifact ?label WHERE {
        {
          {
            SELECT ?artifact (max(?version) as ?maxVersion) WHERE {
              GRAPH ?g2 {
                ?dataset <https://dataid.dbpedia.org/databus#artifact> ?artifact.
                ?dataset <http://purl.org/dc/terms/hasVersion> ?version .
              }
            }
            GROUP BY ?artifact
          }
          GRAPH ?g1 {
            ?dataset <https://dataid.dbpedia.org/databus#artifact> ?artifact .
            ?dataset <http://purl.org/dc/terms/hasVersion> ?maxVersion .
            ?dataset <http://purl.org/dc/terms/title> ?label.
          }
        }
        %VALUES%
      }
  - fieldName: label
    resourceName: account
    query: >
      SELECT DISTINCT ?account ?label WHERE {
        {
          GRAPH ?g {
            ?person <http://xmlns.com/foaf/0.1/account> ?account .
            ?person <http://xmlns.com/foaf/0.1/name> ?label.
          }        
        }
        %VALUES%
      }
  - fieldName: part
    resourceName: artifact
    query: >
      SELECT ?artifact ?part WHERE {
        {
          VALUES ?n { 1 } 
          {
            SELECT DISTINCT ?artifact WHERE {
              GRAPH ?g {
                ?artifact a <https://dataid.dbpedia.org/databus#Artifact>.
              }
            }
          }
          BIND (replace(str(?artifact), ".*?([^\\/]+)$", "$1") AS ?part)
        }
        %VALUES%
      }
  - fieldName: part
    resourceName: artifact
    query: >
      SELECT ?artifact ?part WHERE {
        {
          {
            SELECT DISTINCT ?artifact WHERE {
              GRAPH ?g {
                ?artifact a <https://dataid.dbpedia.org/databus#Artifact>.
              }
            }
          }
          BIND (replace(replace(str(?artifact), "(\\/[^\\/]+)$", ""), ".*?([^\\/]+)$", "$1") AS ?part)
        }
        %VALUES%
      }
  - fieldName: part
    resourceName: artifact
    query: >
      SELECT ?artifact ?part WHERE {
        {
          {
            SELECT DISTINCT ?artifact WHERE {
              GRAPH ?g {
                ?artifact a <https://dataid.dbpedia.org/databus#Artifact>.
              }
            }
          }
          BIND (replace(replace(str(?artifact), "(\\/[^\\/]+){2}$", ""), ".*?([^\\/]+)$", "$1") AS ?part)
        }
        %VALUES%
      }
  - fieldName: part
    resourceName: version
    query: >
      SELECT ?version ?part WHERE {
        {
          {
            SELECT DISTINCT ?version WHERE {
              GRAPH ?g {
                ?version a <https://dataid.dbpedia.org/databus#Version>.
              }
            }
          }
          BIND (replace(str(?version), ".*?([^\\/]+)$", "$1") AS ?part)
        }
        %VALUES%
      }
  - fieldName: part
    resourceName: version
    query: >
      SELECT ?version ?part WHERE {
        {
          {
            SELECT DISTINCT ?version WHERE {
              GRAPH ?g {
                ?version a <https://dataid.dbpedia.org/databus#Version>.
              }
            }
          }
          BIND (replace(replace(str(?version), "(\\/[^\\/]+)$", ""), ".*?([^\\/]+)$", "$1") AS ?part)
        }
        %VALUES%
      }
  - fieldName: part
    resourceName: group
    query: >
      SELECT ?group ?part WHERE {
        {
          {
            SELECT DISTINCT ?group WHERE {
              GRAPH ?g {
                ?group a <https://dataid.dbpedia.org/databus#Group>.
              }
            }
          }
          BIND (replace(str(?group), ".*?([^\\/]+)$", "$1") AS ?part)
        }
        %VALUES%        
      }
  - fieldName: part
    resourceName: group
    query: >
      SELECT ?group ?part WHERE {
        {
          {
            SELECT DISTINCT ?group WHERE {
              GRAPH ?g {
                ?group a <https://dataid.dbpedia.org/databus#Group>.
              }
            }
          }
          BIND (replace(replace(str(?group), "(\\/[^\\/]+)$", ""), ".*?([^\\/]+)$", "$1") AS ?part)
        }
        %VALUES%   
      }
  - fieldName: part
    resourceName: collection
    query: >
      SELECT ?collection ?part WHERE {
        {
          VALUES ?n { 1 3 } 
          {
            SELECT DISTINCT ?collection WHERE {
              GRAPH ?g {
                ?collection a <https://dataid.dbpedia.org/databus#Collection> .
              }
            }
          }
          BIND (replace(str(?collection), "^((.*?)\\/){3}", "pre/") as ?suffix) 
          BIND (concat("^([^\\/]+\\/){", str(?n) ,"}") AS ?reg)
          BIND (replace(replace(str(?suffix), ?reg, ""), "\\/.*$", "") AS ?part)
        }
        %VALUES%   
      }
  - fieldName: part
    resourceName: profile
    query: >
      SELECT DISTINCT ?profile (REPLACE(STR(REPLACE(STR(?profile), "(.*)(/)", "")), "#.*", "") AS ?part) WHERE {
        {
          GRAPH ?g {
            ?profile a <http://xmlns.com/foaf/0.1/PersonalProfileDocument> .
          }
        }
        %VALUES%   
      }
  - fieldName: typeName
    resourceName: resource
    query: >
      SELECT DISTINCT ?resource (REPLACE(STR(?type), "(.*)(/|#)", "") AS ?typeName) WHERE {
        { 
          GRAPH ?g {
            ?resource a ?type.
            VALUES ?type { <https://dataid.dbpedia.org/databus#Artifact> <https://dataid.dbpedia.org/databus#Version> <https://databus.dbpedia.org/system/voc/Service> <https://dataid.dbpedia.org/databus#Group> <https://dataid.dbpedia.org/databus#Collection> <http://xmlns.com/foaf/0.1/PersonalProfileDocument> }
          }
        }
        %VALUES%   
      }
  - fieldName: publisher
    resourceName: resource
    query: >
      SELECT ?resource ?publisher WHERE {
        {
          VALUES ?n { 1 } 
          {
            SELECT DISTINCT ?resource WHERE {
              GRAPH ?g {
                ?resource a ?type.
                VALUES ?type { <https://dataid.dbpedia.org/databus#Artifact> <https://databus.dbpedia.org/system/voc/Service> <https://dataid.dbpedia.org/databus#Group> <https://dataid.dbpedia.org/databus#Collection> <http://xmlns.com/foaf/0.1/PersonalProfileDocument> }
              }
            }
          }
          BIND (replace(str(?resource), "^((.*?)\\/){3}", "pre/") as ?suffix) 
          BIND (concat("^([^\\/]+\\/){", str(?n) ,"}") AS ?reg)
          BIND (replace(replace(str(?suffix), ?reg, ""), "\\/.*$", "") AS ?publisher)
        }
        %VALUES%   
      }
  - fieldName: group
    resourceName: artifact
    query: >
      SELECT ?artifact ?group WHERE {
        {
          VALUES ?n { 2 } 
          {
            SELECT DISTINCT ?artifact WHERE {
              GRAPH ?g {
                ?artifact a <https://dataid.dbpedia.org/databus#Artifact> .
              }
            }
          }
          BIND (replace(str(?artifact), "^((.*?)\\/){3}", "pre/") as ?suffix) 
          BIND (concat("^([^\\/]+\\/){", str(?n) ,"}") AS ?reg)
          BIND (replace(replace(str(?suffix), ?reg, ""), "\\/.*$", "") AS ?group)
        }
        %VALUES%   
      }