PREFIX databus-sys: <https://databus.dbpedia.org/system/ns/core#>
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat:  <http://www.w3.org/ns/dcat#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# Creates a dataset for lucene based databus indexing
CONSTRUCT
{
  ?artifact a dataid:Artifact .
  ?artifact databus-sys:typeName "Artifact" .
  ?artifact databus-sys:typeName "Dataset" .
  ?artifact rdfs:label ?artifactLabel .
  ?artifact rdfs:comment ?artifactDescription .
  ?artifact databus-sys:publisherName ?artifactPublisherName .
  ?publisher a databus-sys:Publisher .
  ?publisher databus-sys:typeName "Publisher" .
  ?publisher rdfs:label ?artifactPublisherName .
  ?service a databus-sys:Service .
  ?service databus-sys:typeName "Service" .
  ?service rdfs:label ?serviceLabel .
  ?service rdfs:comment ?serviceDescription .
  ?service databus-sys:publisherName ?servicePublisherName .
  ?group a dataid:Group .
  ?group databus-sys:typeName "Group" .
  ?group rdfs:label ?groupLabel .
  ?group databus-sys:publisherName ?artifactPublisherName .
}
WHERE
{
  ?artifact a dataid:Artifact .
  ?dataset dataid:artifact ?artifact .
  ?dataset dct:title ?artifactLabel .
  ?dataset rdfs:comment ?artifactDescription .
  ?dataset dct:publisher ?webid .
  ?webid foaf:name ?artifactPublisherName .
  ?webid foaf:account ?publisher .
  ?service a databus-sys:Service .
  ?service dct:title ?serviceLabel .
  ?service dct:abstract ?serviceDescription .
  ?service databus-sys:publisher ?servicePublisher .
  ?serviceWebId foaf:account ?servicePublisher .
  ?serviceWebId foaf:name ?servicePublisherName .
  ?dataset dataid:group ?group .
  BIND( REPLACE( STR(?group), CONCAT(STR(?publisher), "/"), "" ) AS ?groupLabel).

}
