PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat:  <http://www.w3.org/ns/dcat#>
# Get all files
SELECT DISTINCT ?file WHERE {
  ?dataset dataid:artifact <%ARTIFACT_URI%> .
  ?dataset dcat:distribution ?distribution .
  %OPTIONS%
  ?distribution dcat:downloadURL ?file .
}
