PREFIX databus: <http://dataid.dbpedia.org/databus#>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat:  <http://www.w3.org/ns/dcat#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
# Get all files
SELECT DISTINCT 
  ?versionUri
  ?dataset
  ?distribution
  ?title
  ?abstract
  ?description
  (GROUP_CONCAT(DISTINCT ?file; SEPARATOR=", ") AS ?downloadURLs)
  ?license
  ?size
  ?version
  ?format
  (GROUP_CONCAT(DISTINCT ?var; SEPARATOR=', ') AS ?variant)
  ?preview
WHERE { 
  %COLLECTION_QUERY%
  ?distribution dcat:downloadURL ?file .
  ?distribution databus:formatExtension ?format .
  OPTIONAL { ?distribution databus:contentVariant ?var . }
  OPTIONAL { ?distribution dct:license ?license . }
  OPTIONAL { ?distribution dcat:byteSize ?size . }
  ?distribution dct:hasVersion ?version .
  ?dataset dcat:distribution ?distribution .
  ?dataset dataid:version ?versionUri .
  ?dataset dct:title ?title .
  ?dataset dct:abstract ?abstract .
  ?dataset dct:description ?description.
}
GROUP BY ?versionUri ?dataset ?distribution ?title ?description ?license ?size ?version ?format ?preview