PREFIX databus: <https://dataid.dbpedia.org/databus#>
PREFIX dcv: <https://dataid.dbpedia.org/databus-cv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat:  <http://www.w3.org/ns/dcat#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
# Get all files
SELECT DISTINCT 
  ?versionUri
  ?dataset
  ?distribution
  ?title
  ?abstract
  ?description
  (GROUP_CONCAT(DISTINCT ?file; SEPARATOR=", ") AS ?downloadURLs)
  ?license
  ?size
  ?version
  ?format
  (GROUP_CONCAT(DISTINCT ?var; SEPARATOR=', ') AS ?variant)
  ?preview
WHERE { 
  %COLLECTION_QUERY%
  ?distribution dcat:downloadURL ?file .
  ?distribution databus:formatExtension ?format .
  OPTIONAL { ?distribution databus:contentVariant ?var . }
  OPTIONAL { ?distribution dct:license ?license . }
  OPTIONAL { ?distribution dcat:byteSize ?size . }
  ?distribution dct:hasVersion ?versionName .
  ?version dcat:distribution ?distribution .
  ?version a databus:Version .
  ?version dct:title ?title .
  ?version dct:abstract ?abstract .
  ?version dct:description ?description.
}
GROUP BY ?version ?distribution ?title ?description ?license ?size ?versionName ?format ?preview