PREFIX databus: <https://dataid.dbpedia.org/databus#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT DISTINCT ?uri ?title ?abstract ?description WHERE {

GRAPH ?g1 {
    VALUES ?uri {
      <%GROUP_URI%> 
    }
    
    ?uri a databus:Group .
  }
  OPTIONAL { 
    GRAPH ?g2 {
      OPTIONAL {  ?uri dct:title ?title . }
      OPTIONAL {  ?uri dct:abstract ?abstract . }
      OPTIONAL {  ?uri dct:description ?description . }
    }
  }
}