PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>

SELECT * WHERE
{
   ?uri a dataid:Collection .
   ?uri dct:publisher <%ACCOUNT_URI%> .
   ?uri dct:title ?label .
   ?uri dct:abstract ?abstract .
   ?uri dct:description ?description .
   ?uri dataid:content ?content .
   OPTIONAL { ?uri dct:issued ?issued . }
   OPTIONAL { ?uri dct:created ?created . }
}