PREFIX databus: <https://dataid.dbpedia.org/databus#>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat:  <http://www.w3.org/ns/dcat#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?property ?value WHERE {

  {
    GRAPH ?g {
      ?dataset databus:group <%GROUP_URI%> .
      ?dataset dcat:distribution ?distribution .
      ?dataset databus:artifact ?value .
      BIND(databus:artifact AS ?property)
    }
  }
  UNION
  {
    GRAPH ?g {
      ?dataset databus:group <%GROUP_URI%> .
      ?dataset dcat:distribution ?distribution . 
      ?distribution dct:hasVersion ?value .
      BIND(dct:hasVersion AS ?property)
    }
  }
  UNION
  {
    GRAPH ?g {
      ?dataset databus:group <%GROUP_URI%> .
      ?dataset dcat:distribution ?distribution . 
      ?distribution databus:formatExtension ?value .
      BIND(databus:formatExtension AS ?property)
    }
  }
  UNION
  {
    GRAPH ?g {
      ?dataset databus:group <%GROUP_URI%> .
      ?dataset dcat:distribution ?distribution . 
      ?distribution databus:compression ?value .
      BIND(databus:compression AS ?property)
    }
  }
  UNION
  {
    GRAPH ?g {
      ?dataset databus:group <%GROUP_URI%> .
      ?dataset dcat:distribution ?distribution . 
      ?distribution ?property ?value .
      ?property rdfs:subPropertyOf databus:contentVariant .
    }
  }
}
