PREFIX databus: <https://dataid.dbpedia.org/databus#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT DISTINCT ?artifact WHERE
{
  GRAPH ?g {
    ?artifact a databus:Artifact .
    FILTER(STRSTARTS(STR(?artifact), "%ACCOUNT_URI%/"))
  }
}