PREFIX dcat:  <http://www.w3.org/ns/dcat#>
PREFIX databus: <http://dataid.dbpedia.org/databus#>

Select ?downloadUrl {
  GRAPH ?g {
    ?singlefile databus:file <%FILE_URI%> .
    ?singlefile dcat:downloadURL ?downloadUrl .
  }
}
