
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX databus: <https://dataid.dbpedia.org/databus#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


# publisher with number and size of versions
SELECT DISTINCT ?account ?numUploads ?uploadSize WHERE {
  ?account foaf:account <%ACCOUNT_URI%>.
  OPTIONAL {
    SELECT (count(?version) as ?numUploads) WHERE {
      ?account foaf:account <%ACCOUNT_URI%> .
      ?version dct:publisher ?account.
      ?version a databus:Version .
    }
  }
  OPTIONAL {
    SELECT (sum(?size) as ?uploadSize) WHERE {
      ?account foaf:account <%ACCOUNT_URI%> .
      ?version dct:publisher ?account.
      ?version dcat:distribution ?distribution .
      ?distribution dcat:byteSize ?size .
    }
  }
}
