PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX databus: <https://databus.dbpedia.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?ym (SUM(?size) as ?filesize) WHERE {
  GRAPH ?g {
    ?distribution a dataid:Part .
    ?distribution dcat:byteSize ?size .
    ?distribution dct:issued ?date .
    BIND (SUBSTR(STR(?date), 1, 7) AS ?ym)
  }
}
GROUP BY ?ym
ORDER BY ?ym
