PREFIX databus-sys: <https://databus.dbpedia.org/system/voc/>
PREFIX databus: <https://databus.dbpedia.org/>
PREFIX dct:   <http://purl.org/dc/terms/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?app as ?uri ?title ?icon ?abstract ?description ?banner ?homepage ?publisherUri WHERE {
  ?app a databus-sys:Application .
  ?app databus-sys:publisher <%PUBLISHER_URI%> .
  ?app databus-sys:icon ?icon .
  ?app databus-sys:banner ?banner .
  ?app databus-sys:homepage ?homepage .
  ?app dct:title ?title .
  OPTIONAL { ?app dct:abstract ?abstract . }
  OPTIONAL { ?app dct:description ?description . }
  BIND(<%PUBLISHER_URI%> AS ?publisherUri)
}
