PREFIX dct: <http://purl.org/dc/terms/>
PREFIX databus: <http://dataid.dbpedia.org/databus#>

SELECT * WHERE
{
  GRAPH ?g {
    <%COLLECTION_URI%> a databus:Collection .
    <%COLLECTION_URI%> dct:title ?label .
    <%COLLECTION_URI%> dct:publisher ?publisher . 
    <%COLLECTION_URI%> dct:abstract ?abstract .
    <%COLLECTION_URI%> dct:description ?description .
    <%COLLECTION_URI%> databus:collectionContent ?content .
    #<%COLLECTION_URI%> dct:created ?created .
    #<%COLLECTION_URI%> dct:modified ?modified .
    OPTIONAL { <%COLLECTION_URI%> dct:issued ?issued . }
  }
}
