PREFIX databus: <https://dataid.dbpedia.org/databus#>

SELECT ?secretary ?agent ?writeAccess
WHERE {
  <%ACCOUNT_URI%#this> databus:secretary ?secretary .
  ?secretary databus:agent ?agent .
  OPTIONAL { ?secretary databus:hasWriteAccessTo ?writeAccess }
}
