
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX databus: <https://databus.dbpedia.org/>
PREFIX dataiddebug: <http://dataid.dbpedia.org/ns/debug.ttl#>

# Get the information of the latest dataset for a specific artifact
SELECT DISTINCT ?dataset ?uri ?name ?title ?abstract ?description
  ?date ?group ?artifact ?publisher ?license ?attribution
  ?codeReference ?documentationLocation ?feedbackChannel ?issueTracker WHERE {

  GRAPH ?g {
    ?dataset dataid:version <%VERSION_URI%> .
    ?dataset dct:hasVersion ?name.
    ?dataset dct:title ?title.
    ?dataset dct:abstract ?abstract.
    ?dataset dct:description ?description.
    ?dataset dct:issued ?date.
    ?dataset dataid:group ?group .
    ?dataset dataid:artifact ?artifact.
    ?dataset dct:publisher ?publisher.
    ?dataset dct:license ?license.
    OPTIONAL { ?dataset dataid:attribution ?attribution . }
    OPTIONAL { ?dataset dataiddebug:codeReference ?codeReference . }
    OPTIONAL { ?dataset dataiddebug:documentationLocation ?documentationLocation . }
    OPTIONAL { ?dataset dataiddebug:feedbackChannel ?feedbackChannel . }
    OPTIONAL { ?dataset dataiddebug:issueTracker ?issueTracker . }
    BIND(<%VERSION_URI%> AS ?uri)
  }
}
