PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dataiddebug: <http://dataid.dbpedia.org/ns/debug.ttl#>
PREFIX dcat:   <http://www.w3.org/ns/dcat#>

SELECT * WHERE {
  ?dataset dataid:version <%VERSION_URI%> .
  ?dataset dataiddebug:codeReference ?codeReference .
  ?dataset dataiddebug:documentationLocation ?documentationLocation .
  ?dataset dataiddebug:feedbackChannel ?feedbackChannel .
  ?dataset dataiddebug:issueTracker ?issueTracker .
}
