
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX databus: <https://databus.dbpedia.org/>
PREFIX dataiddebug: <http://dataid.dbpedia.org/ns/debug.ttl#>

# Get the information of the latest dataset for a specific artifact
SELECT DISTINCT ?dataset ?label ?comment ?groupdocu ?groupLabel ?description ?license ?date ?version ?uri ?artifactUri ?publisherUri ?codeReference ?documentationLocation ?feedbackChannel ?issueTracker WHERE {

  GRAPH ?g {
    ?dataset dataid:version <%VERSION_URI%> .
    ?dataset dataid:group ?group.
    ?dataset dct:hasVersion ?version.
    ?dataset dct:title ?label.
    ?dataset dct:abstract ?comment.
    ?dataset dct:issued ?date.
    ?dataset dct:license ?license.
    ?dataset dct:description ?description.
    ?dataset dataid:artifact ?artifactUri.
    ?dataset dct:publisher ?publisher.
    OPTIONAL { ?dataset dataid:groupdocu ?groupdocu . }
    OPTIONAL { ?publisher foaf:account ?publisherUri. }
    Optional {  ?group rdfs:label ?groupLabel. }
    OPTIONAL { ?dataset dataiddebug:codeReference ?codeReference . }
    OPTIONAL { ?dataset dataiddebug:documentationLocation ?documentationLocation . }
    OPTIONAL { ?dataset dataiddebug:feedbackChannel ?feedbackChannel . }
    OPTIONAL { ?dataset dataiddebug:issueTracker ?issueTracker . }
    BIND(<%VERSION_URI%> AS ?uri)
  }
}
