PREFIX databus: <http://dataid.dbpedia.org/databus#>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat:  <http://www.w3.org/ns/dcat#>

SELECT DISTINCT ?file WHERE {
  ?dataset databus:artifact <https://databus.dbpedia.org/dbpedia/databus/databus-data> .
  ?dataset dcat:distribution ?distribution .
  ?distribution dct:hasVersion ?latestVersion
  {
    SELECT (?version as ?latestVersion) WHERE {
      ?dataset databus:artifact <https://databus.dbpedia.org/dbpedia/databus/databus-data> .
      ?dataset dct:hasVersion ?version .
    } ORDER BY DESC (?version) LIMIT 1
  }
  ?distribution dcat:downloadURL ?file .
}
