PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT
{
  ?person a foaf:Person .
  ?person a <http://dbpedia.org/ontology/DBpedian> .
  ?person foaf:name ?name .
  ?person foaf:account ?account .
  ?person foaf:img ?image .
  ?person rdfs:comment ?comment .
  ?profile a foaf:PersonalProfileDocument .
  ?profile foaf:maker ?person . 
  ?profile foaf:primaryTopic ?person .
  ?webid foaf:account ?account .

}
WHERE
{
  ?person a foaf:Person .
  ?person foaf:name ?name .
  ?person foaf:account ?account .
  OPTIONAL { ?person foaf:img ?image . }
  OPTIONAL { ?person rdfs:comment ?comment . }
  ?profile a foaf:PersonalProfileDocument .
  ?profile foaf:maker ?person . 
  ?profile foaf:primaryTopic ?person .
  OPTIONAL { ?webid foaf:account ?account . }
}
