PREFIX databus: <https://dataid.dbpedia.org/databus#>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat:  <http://www.w3.org/ns/dcat#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

PREFIX sec: <https://w3id.org/security#>

CONSTRUCT
{
  ?dataset a dataid:Dataset .
  ?dataset ?datasetProperty ?datasetObject .
  ?version a databus:Version .
  ?artifact a databus:Artifact .
  ?distribution a databus:Part .
  ?distribution ?distributionProperty ?distributionObject .
  ?contentVariant ?contentVariantProperty ?contentVariantObject .
  ?proof ?proofProperty ?proofObject .
}
WHERE
{
  ?dataset a dataid:Dataset .
  ?dataset dcat:distribution ?distribution .
  {
    ?dataset ?datasetProperty ?datasetObject .
  }
  UNION
  {
    ?distribution a databus:Part .
    ?distribution ?distributionProperty ?distributionObject .
  }
  UNION
  {
    ?dataset dataid:version ?version .
    ?version a databus:Version .
  }
  UNION
  {
    ?dataset databus:artifact ?artifact .
    ?artifact a databus:Artifact .
  }
  UNION
  {
    ?dataset sec:proof ?proof .
    ?proof ?proofProperty ?proofObject .
  }
  UNION
  {
    ?distribution ?contentVariant ?contentVariantLiteral .
    ?contentVariant ?contentVariantProperty ?contentVariantObject .
    ?contentVariant rdfs:subPropertyOf databus:contentVariant .
  }
}
