PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Creates a collection
CONSTRUCT
{
  ?a ?b ?c . 
}
WHERE
{
  VALUES ?profile { <%RESOURCE_URI%> }
  GRAPH ?g { 
    ?profile a foaf:PersonalProfileDocument .
    ?a ?b ?c . 
  }
}