CREATE TABLE IF NOT EXISTS apikeys (
    apikey VARCHAR(255) NOT NULL PRIMARY KEY,
    keyname VARCHAR(255) NOT NULL,
    sub VARCHAR(255) NOT NULL,
    FOREIGN KEY(sub) REFERENCES users(sub) ON DELETE CASCADE
);